packages:
  - apps/*
  - packages/*

allowBuilds:
  '@parcel/watcher': true # file watching (next-intl)
  '@prisma/engines': true # prisma CLI engines
  '@swc/core': true # NestJS/Next compiler
  esbuild: true # bundler used by tooling
  prisma: true # prisma CLI
  sharp: true # Next.js image optimization
